import React from 'react';
import { notFound } from 'next/navigation';
import { getCollectionProducts } from '@/lib/shopify';
import { ProductCard } from '@/components/product/ProductCard';
import { FilterLayout } from '@/components/product/FilterLayout';

export const dynamic = 'force-dynamic';

export async function generateMetadata({ params }: { params: Promise<{ handle: string }> }) {
  const resolvedParams = await params;
  const collection = await getCollectionProducts(resolvedParams.handle);
  if (!collection) return {};

  const title = collection.seo?.title || collection.title;
  const description = collection.seo?.description || collection.description || '';
  const url = `${process.env.NEXT_PUBLIC_SITE_URL || 'https://cocoman.store'}/collections/${resolvedParams.handle}`;
  const imageUrl = collection.image?.url || '';

  return {
    title,
    description,
    alternates: {
      canonical: url,
    },
    openGraph: {
      title,
      description,
      url,
      images: imageUrl ? [{ url: imageUrl, width: 1200, height: 630 }] : [],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: imageUrl ? [imageUrl] : [],
    },
  };
}

export default async function CollectionPage({
  params,
  searchParams,
}: {
  params: Promise<{ handle: string }>;
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const { handle } = await params;
  const searchParamsResolved = await searchParams;
  
  // Extract sort/filter params
  const sortKey = typeof searchParamsResolved.sort === 'string' ? searchParamsResolved.sort : 'COLLECTION_DEFAULT';
  const reverse = searchParamsResolved.reverse === 'true';

  // Construct Shopify ProductFilters
  const filters: any[] = [];
  
  if (searchParamsResolved.available === 'true') {
    filters.push({ available: true });
  }
  
  if (searchParamsResolved.minPrice || searchParamsResolved.maxPrice) {
    const priceFilter: any = {};
    if (searchParamsResolved.minPrice) priceFilter.min = parseFloat(searchParamsResolved.minPrice as string);
    if (searchParamsResolved.maxPrice) priceFilter.max = parseFloat(searchParamsResolved.maxPrice as string);
    filters.push({ price: priceFilter });
  }

  // Handle dynamic filters generated by Storefront API (JSON strings in the 'filter' param)
  const filterParams = [].concat((searchParamsResolved.filter as any) || []);
  filterParams.forEach(f => {
    if (typeof f === 'string') {
      try {
        filters.push(JSON.parse(f));
      } catch (e) {
        console.error("Failed to parse filter:", f);
      }
    }
  });

  const collection = await getCollectionProducts(handle, sortKey, reverse, filters);

  if (!collection) {
    notFound();
  }

  return (
    <div className="bg-warm-off-white text-jet-black min-h-screen pt-12 md:pt-20 pb-24">
      {/* Collection Header */}
      <header className="px-6 md:px-12 mb-8 md:mb-12 max-w-7xl mx-auto text-center flex flex-col items-center">
        <h1 className="text-3xl md:text-4xl font-serif mb-4 uppercase tracking-tight">
          {collection.title}
        </h1>
        {collection.description && (
          <p className="text-sm font-sans font-light max-w-2xl opacity-70 leading-relaxed">
            {collection.description}
          </p>
        )}
        <div className="mt-4 text-xs font-semibold tracking-widest uppercase opacity-50">
          {collection.products.length} Products
        </div>
      </header>

      {/* Main Content Area */}
      <div className="px-6 md:px-12 max-w-[1600px] mx-auto">
        <FilterLayout availableFilters={collection.availableFilters || []}>
          {collection.products.length === 0 ? (
            <div className="py-20 text-center flex flex-col items-center">
              <p className="text-lg mb-4">No products found in this collection.</p>
            </div>
          ) : (
            <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-x-4 gap-y-12 md:gap-x-8 md:gap-y-16">
              {collection.products.map((product) => (
                <ProductCard key={product.id} product={product} />
              ))}
            </div>
          )}
        </FilterLayout>
      </div>
    </div>
  );
}
